version: '3'

services:
  nest-backend:
    build: 
      context: nest-backend 
    ports: 
      - '3000:3000' 
  vue-frontend:
    build: 
      context: vue-frontend
    ports: 
      - '4173:4173'
    